[book]
title = "Eternal Pixels"
description = "A UI suite and pixel art editor."
authors = ["Eternal Pixels contributors"]
language = "en"
src = "src"

[build]
build-dir = "book"

[output.html]
default-theme = "light"
preferred-dark-theme = "navy"
